server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?useUnicode&characterEncoding=utf-8
    username: root
    password: admin